x-volume: &volume-common
  volumes:
      - shared-workspace:/opt/workspace
      - /home/hyderreza/codehub/ade-pipeline/keys/gcs-credentials.json:/keys/gcs-credentials.json:ro
      - ./jobs:/opt/workspace

x-worker: &worker-common
  image: spark-worker
  environment:
    - SPARK_WORKER_CORES=2
    - SPARK_WORKER_MEMORY=4g
    - GOOGLE_APPLICATION_CREDENTIALS=/keys/gcs-credentials.json
  <<: *volume-common
  depends_on:
    - spark-master

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    <<: *volume-common
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/gcs-credentials.json
  spark-master:
    image: spark-master
    container_name: spark-master
    environment:
      - SPARK_LOCAL_IP=spark-master
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/gcs-credentials.json
    ports:
      - 8080:8080
      - 7077:7077
    <<: *volume-common

  worker-1:
    <<: *worker-common
    container_name: spark-worker-1
    ports:
      - 8081:8081
  worker-2:
    <<: *worker-common
    container_name: spark-worker-2
    ports:
      - 8082:8081
  worker-3:
    <<: *worker-common
    container_name: spark-worker-3
    ports:
      - 8083:8081
  worker-4:
    <<: *worker-common
    container_name: spark-worker-4
    ports:
      - 8084:8081