networks:
  monitor-network:
    name: monitor-network
  shared_network:
    name: shared_network
    external : true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-network
      - shared_network
    depends_on:
      pushgateway:
        condition: service_started
  
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitor-network
      - shared_network
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - monitor-network
      - shared_network
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    depends_on:
      - prometheus