networks:
  monitor-network:
    name: monitor-network
  shared_network:
    name: shared_network
    external : true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volume/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-network
      - shared_network
    depends_on:
      pushgateway:
        condition: service_started
  
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitor-network
      - shared_network
  
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - monitor-network
      - shared_network
    ports:
      - 3000:3000
    volumes:
      - ./volume/grafana:/var/lib/grafana
    depends_on:
      - prometheus

  # ingestion:
  #   image: ade-pipeline/openfda:latest
  #   container_name: ingestion
  #   networks:
  #     - monitor-network
  #   command: >
  #     --year=2004,2005,2006,2007,2008,2009
  #     --max_batch_size_mb=2000 
  #     --metrics_gateway=pushgateway:9091
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     prometheus:
  #         condition: service_started
  #   volumes:
  #     - /home/hyderreza/codehub/ade-pipeline/keys/gcs-credentials.json:/app/gcs-credentials.json:ro
  #   environment:
  #     - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-credentials.json