services:
  openfda:
    container_name: openfda
    networks:
      - ade-network
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-credentials.json
    volumes:
      - /home/hyderreza/codehub/ade-pipeline/keys/gcs-credentials.json:/app/gcs-credentials.json:ro

networks:
  ade-network:
    name: ade-network