global:
  scrape_interval: 5s

scrape_configs:
  # Pushgateway metrics (metrics from multiple apps collected here)
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
